function [result1,tempmodel]=runehmodel(newmodel)
nc=size(newmodel.Se,1);
params = struct();
params.OutputFlag = 0;
tempmodel=newmodel;
tempmodel.A=[newmodel.Sh;newmodel.Sh];
tempmodel.lb=full(newmodel.lb);
tempmodel.ub=full(newmodel.ub);
tempmodel.obj=zeros(size(tempmodel.A,2),1);
tempmodel.obj(newmodel.bmi)=-1;
tempmodel.rhs=full([newmodel.rhslb;newmodel.rhsub]);
tempmodel.sense = [repmat('>',nc,1);repmat('<',nc,1)];
result1 = gurobi(tempmodel,params);